// This file is meant for implementing the functions which will be used throughout multiple unit test files
// Although this file doesn't have the `_test` suffix, it will not be included in production code as long as it is not imported by any production code files
package unittest

import (
	"bufio"
	"fmt"
	"os"
	"testing"
	"time"

	"github.com/gaudiumsoftware/mchlogtoolkitgo/unittest/logger"

	"github.com/gaudiumsoftware/mchlogtoolkitgo"
	"github.com/gaudiumsoftware/mchlogtoolkitgo/mchlogcore"
	_assert "github.com/stretchr/testify/assert"
)

// Used to check the way logs should be matched with the expected logs
// For example, logs from default log files always have the fields "level" and "message"
var defaultLogFiles = []string{"error", "info", "fatal", "warn", "test", "debug"}

// logFiles may include special files that use LogSubject directly from mchlogcore
// All files here will be checked with `CompareLogs()` and be truncated after each test case
// You may add additional log files to this slice by passing them as arguments to `SetupTests()`
var logFiles = []string{"error", "info", "fatal", "warn", "test", "debug"}

// SetupTests is a function that is ran only once when testing a function, before any test cases
// Important: if additional log files are passed, call the returned function to clear them from `logFiles` after the test function finishes
func SetupTests(t *testing.T, additionalLogFiles ...string) (*_assert.Assertions, func()) {
	// Suggestion of the library, because assert is used many times
	assert := _assert.New(t)

	// Initializes a mock of the logger, but only once
	if logger.Logger == nil {
		logger.Level = "debug"
		logger.InitLoggerMock(t)
	}

	// Clear init logs (e.g. "MchLogToolkit initialized") so the first test case starts clean
	truncateLogFiles(t)

	teardown := func() {}

	// If additional log files are passed, they will be added to the logFiles slice
	// This way, their logs will be checked with `CompareLogs()` and they will get truncated after each test case
	if len(additionalLogFiles) > 0 {
		originalLength := len(logFiles)
		logFiles = append(logFiles, additionalLogFiles...)

		teardown = func() {
			logFiles = logFiles[:originalLength]
		}
	}

	return assert, teardown
}

// SetupTestCase is a function that runs before each test case
// It clears log files before each test case and returns a teardown that clears them again after
func SetupTestCase(t *testing.T) func(t *testing.T) {
	// Removes the content of log files created before the test case starts
	truncateLogFiles(t)

	// Returns a tear down function that runs after each test case
	return func(t *testing.T) {
		// Removes the content of log files created during the test case
		truncateLogFiles(t)
	}
}

// Compares the expected logs of a test case with the actual logs generated by running the test case
func CompareLogs(t *testing.T, assert *_assert.Assertions, expectedLogs map[string][]string) {
	// Checks if any logs to log files were made that shouldn't have been
	for _, logFile := range logFiles {
		// No expected logs for this log file
		if expectedLogs[logFile] == nil {
			if logFileExists(logFile) && !isLogFileEmpty(logFile) {
				t.Error("Log file", logFile, "should be empty or not exist, but has the following content instead:", getLogMessages(t, logFile))
			}
		}
	}

	// For all files that have expected logs, check if the logs are correct
	for expectedLogFile := range expectedLogs {
		isDefaultLogFile := false
		for _, defaultLogFile := range defaultLogFiles {
			if expectedLogFile == defaultLogFile {
				isDefaultLogFile = true
				break
			}
		}

		expectedMessages := expectedLogs[expectedLogFile]
		logMessages := getLogMessages(t, expectedLogFile)

		if len(logMessages) != len(expectedMessages) {
			t.Errorf("Expected %d log messages in %s log file, but got %d instead: %v", len(expectedMessages), expectedLogFile, len(logMessages), logMessages)
			continue
		}

		// Compare the expected logs with the actual logs
		for i := range logMessages {
			if isDefaultLogFile {
				// The logs from default log files include the level, line, message, among other fields
				// For default log files, only the level, message and timestamp fields will be checked
				assert.Contains(logMessages[i], `"level":"`+expectedLogFile+`"`)

				// No closing `"` because "message" may be contain errors that have different endings per machine
				assert.Contains(logMessages[i], `"message":"`+expectedMessages[i])
			} else {
				// If it's not a default log file, the log will be exactly as it's written
				assert.Contains(logMessages[i], expectedMessages[i])
			}

			// The timestamp is present in both default and non-default log files
			timeNowUtc := time.Now().UTC().Format("2006-01-02 15:04:05")
			assert.Contains(logMessages[i], `"timestamp":"`+timeNowUtc+`"`)
		}
	}
}

func logFileExists(subject string) bool {
	// Get the log file's name
	fileName := mchlogcore.MchLog.GetFileNameFromStreamName(subject)

	// Checks if the log file exists
	if _, err := os.Stat(fileName); os.IsNotExist(err) {
		return false
	}

	return true
}

func isLogFileEmpty(subject string) bool {
	// Get the log file's name
	fileName := mchlogcore.MchLog.GetFileNameFromStreamName(subject)

	// Gets the information about the log file
	info, err := os.Stat(fileName)
	if err != nil {
		// If the file doesn't exist, it is considered empty
		return true
	}

	// Checks if the log file is empty
	if info.Size() != 0 {
		return false
	}

	return true
}

// Get all log messages from a log file and returns it as a slice of strings
func getLogMessages(t *testing.T, subject string) []string {
	// Get the log file's name
	fileName := mchlogcore.MchLog.GetFileNameFromStreamName(subject)

	f, err := os.Open(fileName)
	if err != nil {
		t.Errorf("Error opening log file: %v", err)
		return nil
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			t.Errorf("Error closing log file: %v", closeErr)
		}
	}()

	var logMsgs []string

	// Read the contents of the log file, line by line, and append it to the logMsgs slice
	fileScanner := bufio.NewScanner(f)
	for fileScanner.Scan() {
		logMsgs = append(logMsgs, fileScanner.Text())
	}

	return logMsgs
}

func RemoveLogFiles() error {
	return os.RemoveAll(mchlogtoolkitgo.DebugPath)
}

// RunTests wraps testing.M so applog/ created under the package cwd is removed
// before and after the suite. Use it from TestMain in packages that call SetupTests:
//
//	func TestMain(m *testing.M) {
//		unittest.RunTests(m)
//	}
func RunTests(m *testing.M) {
	if err := RemoveLogFiles(); err != nil {
		fmt.Println("Failed to remove log files before the tests:", err)
	}

	code := m.Run()

	if err := RemoveLogFiles(); err != nil {
		fmt.Println("Failed to remove log files after all tests:", err)
		os.Exit(1)
	}

	os.Exit(code)
}

// Truncate the log files to 0 bytes to avoid interference between tests
// The log files are truncated instead of removed because mchlogtoolkit will mark the file name to not be created again
func TruncateLogFile(t *testing.T, subject string) {
	// Get the log file's name
	file_name := mchlogcore.MchLog.GetFileNameFromStreamName(subject)

	f, err := os.OpenFile(file_name, os.O_RDWR|os.O_TRUNC, 0644)
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()

	err = f.Truncate(0)
	if err != nil {
		t.Fatal(err)
	}
}

func truncateLogFiles(t *testing.T) {
	for _, logFile := range logFiles {
		// Get the log file's name
		file_name := mchlogcore.MchLog.GetFileNameFromStreamName(logFile)
		if _, err := os.Stat(file_name); err == nil {
			TruncateLogFile(t, logFile)
		}
	}
}
